name: sync_service
description: "A robust offline-first syncing solution for Flutter applications, 
leveraging Firestore and Sembast. Offers a flexible framework for custom syncing logic, 
built on the Domain-Driven Design (DDD) principle. Provides pre-implemented syncing logic 
for Firestore and Sembast, ensuring seamless data synchronization across devices, even when offline."
version: 0.0.1
homepage: https://github.com/lhengl/sync_service

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dart_mappable: ^4.2.2
  easy_debounce: ^2.0.3
  cloud_firestore: ^5.2.1
  sembast: ^3.7.2
  device_info_plus: ^10.1.2
  path: ^1.9.0
  path_provider: ^2.1.4
  duration: ^4.0.3
  flutter_kronos: ^0.1.0+1
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.11
  dart_mappable_builder: ^4.2.3
  fake_cloud_firestore: ^3.0.3